FROM i386/alpine:latest

RUN apk update
RUN apk add xvfb
RUN apk add wine

ENV DISPLAY=:0.0
RUN wine winver

ENV PSYQ_PATH=Z:\\app
ENV COMPILER_PATH=Z:\\app
ENV ASSEMBLER_PATH=Z:\\app
ENV LINKER_PATH=Z:\\app
ENV LIBRARY_PATH=Z:\\app\\lib
ENV C_INCLUDE_PATH=Z:\\app\\include
ENV CPLUS_INCLUDE_PATH=Z:\\app\\include
WORKDIR /app
COPY . /app/
