name: Push PSY-Q Docker image
on:
  push:
    branches:
      - master
    paths:
      - 'Dockerfile'
  workflow_dispatch:

jobs:
  update-progress:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ["4.0", "4.1", "4.3", "4.6"]
    steps:
      - name: Clone main repository
        uses: actions/checkout@v2
      - name: Build image
        run: |
          cd psyq${{ matrix.version }}
          docker build -t xeeynamo/psyq:${{ matrix.version }} ..
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push image
        run: docker push xeeynamo/psyq:${{ matrix.version }}
